# Generated by Django 6.0.1 on 2026-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='status_stoc',
            field=models.CharField(default='In Stoc', max_length=100),
            preserve_default=False,
        ),
    ]
