# Generated by Django 6.0.1 on 2026-01-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_produs_status_stoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='status_stoc',
        ),
    ]
